### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by q32784307** [daipeihust/DPScrollNumberLabel#14]
大佬您好，我想问一下，这个我想扩展一下，就是如果是1位数的话，前面补0的操作。这个如何处理？我看demo中是用number类型接收的，如果处理的话好像改动很大啊。有没有好的方案

**Comment by daipeihust** [comment]
https://github.com/daipeihust/DPScrollNumberLabel/blob/99696433cd1326bba001f4fc3ed686b0fcad009f/DPScrollNumberLabel/DPScrollNumberLabel.h#L180

可以用这个接口 设置rowNumber

**Comment by q32784307** [comment]
&nbsp;[[DPScrollNumberLabel alloc] initWithNumber:@(0) fontSize:48 signSetting:SignSettingUnsigned rowNumber:2];
大佬，好像不行啊...
修改你demo里的调用，这样的话，初始化默认的是00。点击+1,就变成了1，前面还是没有0。还是说我还需要修改别的地方?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "daipeihust/DPScrollNumberLabel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 中午12:12
***@***.***&gt;;
抄送:&nbsp;"╋ ゃ. ...***@***.******@***.***&gt;;
主题:&nbsp;Re: [daipeihust/DPScrollNumberLabel] 您好 (Issue #14)





 
https://github.com/daipeihust/DPScrollNumberLabel/blob/99696433cd1326bba001f4fc3ed686b0fcad009f/DPScrollNumberLabel/DPScrollNumberLabel.h#L180
 
可以用这个接口 设置rowNumber
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daipeihust** [comment]
不应该吧 我回头看看

**Comment by q32784307** [comment]
我用你的demo看是这样的……





------------------ 原始邮件 ------------------
发件人: DP ***@***.***&gt;
发送时间: 2021年12月23日 12:31
收件人: daipeihust/DPScrollNumberLabel ***@***.***&gt;
抄送: q32784307 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [daipeihust/DPScrollNumberLabel] 您好 (Issue #14)





 
不应该吧 我回头看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by q32784307** [comment]
大佬，有结果了吗





------------------ 原始邮件 ------------------
发件人: DP ***@***.***&gt;
发送时间: 2021年12月23日 12:31
收件人: daipeihust/DPScrollNumberLabel ***@***.***&gt;
抄送: q32784307 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [daipeihust/DPScrollNumberLabel] 您好 (Issue #14)





 
不应该吧 我回头看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daipeihust** [comment]
暂时没时间搞这个 你看看改动一下代码 应该不复杂的

**Comment by daipeihust** [comment]
最新的提交加入了一个minRowNumber的属性，设置这个值就可以实现了

**Comment by q32784307** [comment]
好嘞，感谢大佬





------------------ 原始邮件 ------------------
发件人: DP ***@***.***&gt;
发送时间: 2021年12月26日 12:25
收件人: daipeihust/DPScrollNumberLabel ***@***.***&gt;
抄送: q32784307 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [daipeihust/DPScrollNumberLabel] 您好 (Issue #14)





 
最新的提交加入了一个minRowNumber的属性，设置这个值就可以实现了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
