### ISSUE TITLE
数字展示

### ISSUE THREAD

**Issue by XinYangLK** [daipeihust/DPScrollNumberLabel#6]
当数字位数达到多位，例如达到6位数，再减少位数的时候，例如减少到两位，前面空出的4位都成了0，有点水电表的意思，能不能优化一下，不让前面有空白0的存在呢，是几位就展示几位，只是建议，或许楼主有别的考虑

**Comment by daipeihust** [comment]
这个问题确实考虑过，之前的方案是前面不会有多余的0，后来改成了现在的方案，当然不同的需求就会有不同的方案，我加一个设置项吧，这样就能满足不同的需求

**Comment by daipeihust** [comment]
已经改好了，在develop分支。

**Comment by XinYangLK** [comment]
多谢采纳



发自我的小米手机在 代培 <notifications@github.com>，2018年1月3日 下午1:31写道：已经改好了，在develop分支。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/daipeihust/DPScrollNumberLabel","title":"daipeihust/DPScrollNumberLabel","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/daipeihust/DPScrollNumberLabel"}},"updates":{"snippets":[{"icon":"PERSON","message":"@daipeihust in #6: 已经改好了，在develop分支。"}],"action":{"name":"View Issue","url":"https://github.com/daipeihust/DPScrollNumberLabel/issues/6#issuecomment-354940018"}}}
